### ISSUE TITLE
Tp terminé

### ISSUE THREAD

**Issue by arimoussa** [PolytechLyon/2019-isi3-graph-ari_benismail#1]
Bonjour Monsieur,

Nous venons de terminer le Tp et souhaitons vous faire part de cela.
Vous trouverez dans le rapport les explications de nos implementations.

Bonne lecture

**Comment by Slashgear** [comment]
Vous avez des `^` au milieu de votre rapport, c'est voulu ? 

Vous avez quelques souci de `format` dans votre code, ce n'est pas très régulier => ce n'est donc pas agréable à lire.

Sinon  les patterns sont compris, tp terminé
